apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-test2
  name: letsencrypt-test2
spec:
 acme:
  email: shah.ac@husky.neu.edu
  privateKeySecretRef:
    name: letsencrypt-privatekey
  server: https://acme-v02.api.letsencrypt.org/directory
  solvers:
  - http01:
      ingress:
        class: nginx
